### ISSUE TITLE
Sending github.token unnecessarily?

### ISSUE THREAD

**Issue by eest** [ko-build/setup-ko#32]
Hello,

When using setup-ko in an action I noticed it was doing this to figure out what version of `ko` to use:
```
curl -L -s -u username:*** https://api.github.com/repos/ko-build/ko/releases/latest
```

The `***` value is a masked `github.token` as seen here: https://github.com/ko-build/setup-ko/blob/3aebd0597dc1e9d1a26bcfdb7cbeb19c131d3037/action.yml#L28

Reading https://docs.github.com/en/actions/security-guides/automatic-token-authentication it states
```
The token's permissions are limited to the repository that contains your workflow.
```

Given that this action is run in my repo, would this mean that we are actually sending a secret even if it is not improving anything (like increasing rate limits for requests)? I realize that the secret is ephemeral but it still feels a bit unnecessary in that case?

**Comment by eest** [comment]
I can also add that there exists a functional problem with sending this secret. I ran into this when trying to use the `setup-ko` workflow on a custom forgejo instance via their version of actions (https://forgejo.org/docs/latest/admin/actions/).

It would fail like so:
```
++ jq -r .tag_name
++ curl -L -s -u username:*** https://api.github.com/repos/ko-build/ko/releases/latest
+ tag=null
+ os=Linux
+ [[ Linux == \m\a\c\O\S ]]
+ [[ ! -z null ]]
+ echo 'Installing ko @ null for Linux'
Installing ko @ null for Linux
+ sudo tar xzf - -C /usr/local/bin ko
+ curl -fsL https://github.com/ko-build/ko/releases/download/null/ko_ull_Linux_x86_64.tar.gz
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

The reason `tag` becomes `null` is because the `github.token` format created by forgejo seems particularly disliked by github, resulting in this response:
```
{
  "message": "Bad credentials",
  "documentation_url": "https://docs.github.com/rest",
  "status": "401"
}
```

Because of this there is no `.tag_name` for `jq` to parse out, so it returns `null`. Interestingly, if I set some random short string as the secret, e.g.: `curl -L -s -u username:foobar https://api.github.com/repos/ko-build/ko/releases/latest` I do get a response (with the 60 reqs/hour rate limit as is documented for unauthenticated requests).

**Comment by cpanato** [comment]
Using the unauthenticated requests seems ok, I guess, but that will be based on the IP, I don't know how GitHub runners do the IP assignment to the runners. If we have a bunch of requests from the same IP runner that will fail :/

also, on the other hand, we are using the default GitHub.token that gets injected into the job and has the default permissions or the ones you set in your workflow; if nothing is set, it has the one we need to read the data.


cc @imjasonh

**Comment by imjasonh** [comment]
I believe we added the `github.secret` to get around rate limits when fetching the latest release.

The issue with forgejo seems to be an issue between GH and that service, and not something I think we can/should fix in this action. This action only expects to be run in GitHub Actions, and is only tested in that environment.

**Comment by eest** [comment]
I got the impression from the docs that the token is only valid for use within the repo running the workflow, if it also gets more API calls towards other repos then I can see why it is used.

**Comment by eest** [comment]
Yeah, sorry about the confusion. I threw together a small workflow in a repo of my own to validate this:
```
Run curl -i -L -s -u username:foobar https://api.github.com/repos/ko-build/ko/releases/latest
HTTP/2 200 
[...]
x-ratelimit-limit: 60
x-ratelimit-remaining: 59
```
vs.
```
Run curl -i -L -s -u "username:***" https://api.github.com/repos/ko-build/ko/releases/latest
HTTP/2 200 
[...]
x-ratelimit-limit: 5000
x-ratelimit-remaining: 4999
```

So you are correct, the token makes it count as authenticated even if interacting with the API of another repo. Still interesting that I can get away with the secret "foobar" and get an unauthenticated response while the token created by forgejo results in an error but that is another story. Given that using the token actually does help with the rate limit I am OK with closing this if you do not see the forgejo use case as relevant. Thanks for taking the time to respond!
